### ISSUE TITLE
iOS 8.0.2 loses connection and all MIDI if locked

### ISSUE THREAD

**Issue by aronnelson** [petegoodliffe/PGMidi#14]
If I lock my iPad (i.e. put it to sleep using the power button). After a short while, after awaking it, the MIDI interface is inoperable. The MIDI app does see the interface but send MIDI doesn't work at all.

**Comment by johndpope** [comment]
have a look at https://github.com/krevis/MIDIApps/tree/master/Frameworks/SnoizeMIDI

**Comment by aronnelson** [comment]
John,

Thank you. I will check it out!

Aron


Aron
http://www.aronnelson.com
http://www.diystompboxes.com/

**Comment by aronnelson** [comment]
It looks like the main change is: 
if (sMIDIClientRef) {
+        MIDIClientDispose(sMIDIClientRef);
+        sMIDIClientRef = NULL;
+    }

Then the sharedClient is released. Will try this and see what terrible things happen!

**Comment by aronnelson** [comment]
OK, ignore this. Yes, certain MIDI interfaces fail, but apparently only a few. M-Audio UNO is one. You can get a generic interface that works perfectly every time so I will mark this as a problem with only certain interfaces.
